### ISSUE TITLE
有没有遇到过sendMessageToGroup一个账号用了一段时间就不能用的情况，换个账号就可以

### ISSUE THREAD

**Issue by MarsZhu2541** [itbaima-study/itbaima-robot-starter#5]
`package com.mars.webchat.util;

import com.mars.webchat.service.impl.ChatGPTServiceImpl;
import jakarta.annotation.Resource;
import lombok.extern.slf4j.Slf4j;
import net.itbaima.robot.event.RobotListener;
import net.itbaima.robot.event.RobotListenerHandler;
import net.itbaima.robot.listener.MessageListener;
import net.itbaima.robot.service.RobotService;
import net.mamoe.mirai.Bot;
import net.mamoe.mirai.event.events.GroupMessageEvent;
import net.mamoe.mirai.message.data.At;
import net.mamoe.mirai.message.data.PlainText;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;

@Slf4j
@RobotListener
public class NormalGroupListener extends MessageListener {

    @Value("${itbaima.robot.username}")
    private long qqNumber;

    @Autowired
    private ChatGPTServiceImpl chatGPTServiceImpl;

    @Autowired
    private RobotService robotService;

    @RobotListenerHandler
    public void handleMessage(GroupMessageEvent event) {
        String message = event.getMessage().contentToString();
        if (!(event.getMessage().get(1) instanceof At)) {
            return;
        }
        if (((At) event.getMessage().get(1)).getTarget() != qqNumber) {
            return;
        }
        log.info("Received group message: {}", message);
        try {
            String chat = chatGPTServiceImpl.chat(message);
            log.info("Sent group message: {}", chat);
            robotService.sendMessageToGroup(event.getGroup().getId(), chat);
        } catch (Exception e) {
            log.error("Error when send message: ", e);
            robotService.sendMessageToGroup(event.getGroup().getId(), "出错了，请联系管理员");
        }
    }
}
`

**Comment by MarsZhu2541** [comment]
似乎一个账号一天只能调用二十次

**Comment by Ketuer** [comment]
> 似乎一个账号一天只能调用二十次

账号密码登录试试看，目前我用着还比较稳定，这个看号

**Comment by MarsZhu2541** [comment]
用密码登陆有没有遇到过这个问题
`Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2700547209), code=45, title=禁止登录, message=登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。, errorInfo=)
`
